steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['install', '.']
  env: ['PROJECT_ROOT=hello']
- name: 'gcr.io/cloud-builders/go'
  args: ['build', 'hello']
  env: ['PROJECT_ROOT=hello']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
  env: ['PROJECT_ROOT=hello']
timeout: '1600s'
artifacts:
  objects:
    location: 'gs://boxapp-219304.appspot.com/'
    paths: ['hello']
